/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/desk2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/desk2.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-2.322, 0.37, 0]} scale={[0.808, 0.391, 0.299]}>
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube002_4.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube002_5.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube002_6.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube002_7.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube002_8.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube002_9.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/desk2.glb')
